version: '3.3'
services:
  api:
    env_file:
      - .env
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - express-mongo
    ports:
      - ${PORT}:3000
    restart: always
    
networks:
  express-mongo:
    driver: bridge