"use client";
import { SmileTwoTone } from "@ant-design/icons";

export const metadata = {
  title: "QuacQuac App",
  description: "Generated by Duc",
};

export default function Home() {
  return (
    <main className="items-center">
      <h1 className="uppercase font-bold text-[25px] text-center text-blue-500">
        Welcome to Quac Quac App!!! Just relax!!!!{" "}
      </h1>
      <SmileTwoTone className="text-[40px]" />
    </main>
  );
}
