"use client";
import LayoutPages from "@/components/LayoutPages";
import { SmileTwoTone } from "@ant-design/icons";

export const metadata = {
  title: "QuacQuac App",
  description: "Generated by Duc",
};

export default function Home() {
  return (
    <main className="items-center">
      <h1 className="uppercase font-bold text-[25px] text-center text-blue-500">
        Welcome to Quac Quac App!!! Just a small demo app!!!!{" "}
      </h1>
      <SmileTwoTone className="text-[40px] flex justify-center" />
    </main>
  );
}

Home.getLayout = ({ page, pageProps }) => (
  <LayoutPages {...pageProps}>{page}</LayoutPages>
);
